Supporting table mapping
ClickHouse/clickhouse-kafka-connect pull request #211
Opened 2023-10-11 06:37 UTC by Paultagoras

This adds a new setting to allow customers to specify a mapping between topic and table names (without a transformer)

2023-10-11 07:18 UTC, mzitnik requested changes
Please provide also tests

2023-10-11 07:18 UTC, mzitnik commented on src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java
> +//            Table table = this.mapping.get(Utils.escapeTopicName(topic));
Lets remove it

2023-10-11 11:50 UTC, mshustov commented on src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java
> +        Table table = this.mapping.get(Utils.getTableName(topic, csc.getTopicToTableMap()));
What about `describeTable`? We need to get metadata from another table  https://github.com/ClickHouse/clickhouse-kafka-connect/blob/374227d099367c0ae8480a4fae6dd8f63d5f90b6/src/main/java/com/clickhouse/kafka/connect/sink/db/helper/ClickHouseHelperClient.java#L135

2023-10-12 11:21 UTC, mshustov commented on src/main/java/com/clickhouse/kafka/connect/sink/ClickHouseSinkConfig.java
> +    public static final String TABLE_MAPPING = "tableMapping";
in bigquery connector it's called `topic2TableMap, in snowflake connector `topic2table.map`

2023-10-12 16:12 UTC, mzitnik approved these changes

2023-10-12 16:13 UTC, merged